"use client";

import Image from "next/image";
import { useEffect, useState } from "react";

const MAPS_URL = "https://www.google.com/maps/search/?api=1&query=%E6%B2%99%E6%87%B7%E9%9B%AA%E8%8C%84%E9%A4%A8%E6%97%97%E8%89%A6%E5%BA%97%20%E9%AB%98%E9%9B%84%E5%B8%82%E6%96%B0%E8%88%88%E5%8D%80%E6%96%B0%E7%94%B0%E8%B7%AF17%E8%99%9F";
const FACEBOOK_URL = "https://www.facebook.com/savoycigar/";
const INSTAGRAM_URL = "https://www.instagram.com/savoycigar_/";

const businessJsonLd = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "沙懷雪茄館旗艦店", alternateName: "Savoy Cigar Kaohsiung Flagship", telephone: "+886-7-281-7778", address: { "@type": "PostalAddress", streetAddress: "新田路17號", addressLocality: "新興區", addressRegion: "高雄市", postalCode: "800", addressCountry: "TW" }, openingHoursSpecification: [{ "@type": "OpeningHoursSpecification", dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], opens: "13:30", closes: "02:30" }], hasMap: MAPS_URL };

const copy = {
  zh: {
    legal: "吸菸有害健康｜未滿20歲不得吸菸及購買菸品｜本網站僅提供門市與空間資訊",
    nav: ["店家介紹", "空間環境", "初次造訪", "品鑑知識", "造訪資訊"], navigate: "立即導航", maps: "Google Maps 導航", call: "致電",
    hero: ["沙懷雪茄館旗艦店", "高雄雪茄品鑑空間", "在 Savoy Blue 的光影裡，留一段時間給雪茄文化、從容交流與高雄城市夜晚的細膩節奏。"], address: ["新興區新田路17號", "每日 13:30–02:30", "20歲以上"],
    about: ["店家介紹", "不急著定義品味，", "讓每次停留自然留下記憶。", "沙懷雪茄館旗艦店位於高雄市新興區，是一處為成熟品味、從容交流與城市夜生活而生的質感空間。\n\n以品牌代表色「沙懷藍」為視覺主調，融合沉穩灰藍色系、溫潤木質地板與柔和燈光，營造內斂、優雅而不拘謹的氛圍。空間串連舒適的座席交流區、富有個性的藝術角落，以及明亮且層次分明的雪茄展示空間，讓每一次停留都能保有恰到好處的距離與節奏。\n\n館內提供精選古巴雪茄、各式酒類、特色調酒與餐飲服務。無論是初次接觸雪茄，或已建立自己的品鑑偏好，都能在專業且自然的介紹下，找到適合當下心情與場合的選擇。\n\n沙懷藍，不只是一種色彩，更代表沙懷所呈現的生活態度——沉著、深邃、從容，並保留一點屬於夜晚的神祕感。\n\n在這裡，雪茄不只是品味的象徵，而是一段值得慢下來感受的時間。"],
    space: ["空間與環境", "灰藍色調、木質地板與柔和照明，串連座席交流區、藝術角落與明亮展示空間。"],
    spaceCards: [["多層次座席", "單椅、沙發與多人座席錯落配置，從個人停留到好友交流，都能找到合適的空間節奏。"], ["藝術交流角落", "灰藍牆面、植栽圖樣與藝術作品，在較小尺度的座席區裡形成安定而有個性的氛圍。"], ["明亮展示空間", "拱形線條、吊燈與光帶展示櫃，讓材質細節與陳列物件清楚呈現。"]],
    gallery: [["沉穩開闊的交流座席", "沙懷雪茄館旗艦店拱形門框與多人交流座席"], ["花卉牆面的舒適座席", "沙懷雪茄館旗艦店花卉牆面、藍色單椅與白色沙發座席"], ["俐落通透的展示區", "沙懷雪茄館旗艦店明亮展示櫃與室內陳列空間"], ["藝術與植栽圖樣交會", "沙懷雪茄館旗艦店藝術畫作與圓弧單椅交流角落"], ["吊燈下的展示光影", "沙懷雪茄館旗艦店吊燈與光帶玻璃展示櫃"], ["座席與展示區自然串連", "沙懷雪茄館旗艦店座席與展示區室內全景"], ["灰藍牆面的細緻層次", "沙懷雪茄館旗艦店灰藍牆面、藝術作品與單椅座席"]],
    guide: ["初次造訪指南", "第一次來不用有壓力，從偏好的香氣與時間開始即可。"], guideCards: [["告訴我們你的偏好", "可從濃淡、香氣、可接受的品鑑時間開始，不需要先懂品牌。"], ["選擇合適的雪茄", "依風味、尺寸與當天狀態，取得容易理解且不過度複雜的介紹。"], ["放慢節奏品鑑", "保持從容頻率，感受前、中、後段的香氣與口感變化。"], ["記下自己的感受", "沒有標準答案；記住喜歡與不喜歡的方向，就是下一次的起點。"]],
    knowledge: ["雪茄品鑑與保存知識", ["品鑑時先感受什麼？", "先觀察燃燒、香氣、濃度與口感，再留意前段到後段的變化。每個人的感受不同，不需追求固定答案。"], ["品鑑節奏如何掌握？", "雪茄適合慢慢感受，間隔過短可能使燃燒溫度升高並影響風味；保持舒適節奏即可。"], ["居家保存的基本原則", "放置於專用保濕盒，避免陽光、熱源、冰箱及劇烈溫濕度變化。常見參考環境約為相對濕度 65–70%、溫度 18–21°C，並依雪茄與設備狀況調整。"], ["需要定期檢查什麼？", "查看保濕設備、濕度計與雪茄外觀，注意乾裂、過濕或異味；不同雪茄也可視需要分區保存。"]],
    visit: ["營業、交通與導航", "三項造訪資訊集中呈現，不在其他區塊重複。", "每日營業", "交通資訊", "開啟即時路線", "特殊節日異動請以 Google 商家檔案為準。", "本站僅提供 Google Maps 路線導航。", "查看目前位置至沙懷雪茄館旗艦店的建議路線。"],
    contact: ["電話及社群連結", "透過官方 Facebook 與 Instagram，掌握沙懷雪茄館的最新消息。", "前往官方 Facebook", "前往官方 Instagram"],
    notice: ["年齡與法規提醒", "本網站僅提供實體門市、空間與品鑑知識資訊，不提供線上菸品交易。進入門市及購買菸品須符合臺灣現行法規與店內規範；如有年齡疑慮，現場人員將要求出示證件。", "未滿20歲不得吸菸及購買菸品", "吸菸有害健康"], footerAddress: "高雄市新興區新田路17號", health: "吸菸有害健康　｜　孕婦吸菸易導致胎兒早產及體重不足　｜　未滿20歲不得吸菸及購買菸品",
  },
  en: {
    legal: "Smoking is harmful to health | Tobacco products are prohibited for persons under 20 | This website provides store and space information only",
    nav: ["About", "The Space", "First Visit", "Cigar Knowledge", "Visit"], navigate: "Get Directions", maps: "Google Maps", call: "Call",
    hero: ["Savoy Cigar Flagship", "Kaohsiung Cigar Tasting Lounge", "In the glow of Savoy Blue, make time for cigar culture, unhurried conversation, and the refined rhythm of Kaohsiung after dark."], address: ["No. 17, Xintian Rd., Xinxing Dist.", "Daily 13:30–02:30", "20+ only"],
    about: ["ABOUT", "There is no need to define taste.", "Let every visit leave its own memory.", "Savoy Cigar Flagship, located in Xinxing District, Kaohsiung, is a refined space created for discerning taste, relaxed conversation, and the rhythm of city nightlife.\n\nBuilt around Savoy Blue, the brand’s signature color, its visual language balances composed blue-grey tones, warm wood flooring, and soft lighting to create an understated, elegant atmosphere that never feels formal. Comfortable seating areas, distinctive art corners, and a bright, layered cigar display gallery are connected throughout, allowing every visit to find its own measured pace and just the right degree of privacy.\n\nThe lounge offers a curated selection of Cuban cigars, wines and spirits, signature cocktails, and dining. Whether you are new to cigars or have developed your own tasting preferences, our team offers professional yet natural guidance to help you find a choice suited to the moment and occasion.\n\nSavoy Blue is more than a color. It expresses the way of life at Savoy: composed, deep, unhurried, with a trace of the mystery that belongs to the night.\n\nHere, a cigar is more than a symbol of taste. It is an invitation to slow down and savor a moment worth experiencing."],
    space: ["The Space", "Blue-grey tones, wood flooring, and gentle lighting connect social seating, artful corners, and a bright display gallery."],
    spaceCards: [["Layered seating", "Armchairs, sofas, and shared seating create an easy rhythm for a quiet pause or time with friends."], ["Artful conversation corners", "Blue-grey walls, botanical patterns, and artwork shape an intimate setting with a distinct sense of character."], ["Illuminated display gallery", "Arched lines, chandeliers, and illuminated cases bring the materials and display details into focus."]],
    gallery: [["An open lounge for conversation", "Arched doorway and lounge seating at Savoy Cigar Flagship"], ["A comfortable floral-wall seating area", "Floral wall, blue armchairs, and white sofa at Savoy Cigar Flagship"], ["A clear, refined display area", "Illuminated display cases at Savoy Cigar Flagship"], ["Where art meets botanical texture", "Artwork and curved lounge chairs at Savoy Cigar Flagship"], ["Display lighting beneath the chandelier", "Chandelier and illuminated glass display at Savoy Cigar Flagship"], ["Seating and display, naturally connected", "Interior overview of Savoy Cigar Flagship"], ["Subtle layers of blue-grey", "Blue-grey wall and lounge seating at Savoy Cigar Flagship"]],
    guide: ["Your First Visit", "No pressure is needed on your first visit. Start with the aromas you enjoy and the time you have."], guideCards: [["Tell us your preference", "Begin with strength, aroma, or how much time you would like to spend. You do not need to know the brands first."], ["Choose a fitting cigar", "Explore approachable guidance based on flavor, size, and how you feel that day."], ["Take your time", "Keep an easy pace and notice how aroma and texture change from the first third to the finish."], ["Remember what you notice", "There is no single right answer. What you enjoy is the best starting point for your next visit."]],
    knowledge: ["Cigar Tasting & Storage", ["What should I notice first?", "Start with the burn, aroma, body, and texture, then notice how they evolve. Every palate is different; there is no fixed answer."], ["How should I pace a cigar?", "Cigars are best enjoyed slowly. Drawing too frequently may raise the burn temperature and affect flavor, so keep a comfortable rhythm."], ["The basics of home storage", "Use a dedicated humidor and avoid sunlight, heat sources, refrigerators, and sharp changes in temperature or humidity. A common reference is 65–70% relative humidity and 18–21°C, adjusted for your cigars and equipment."], ["What should I check regularly?", "Check the humidification equipment, hygrometer, and cigar wrappers for dryness, excess moisture, or off-aromas. Different cigars may also benefit from separate storage."]],
    visit: ["Hours, Location & Directions", "Three essential visit details, gathered in one place.", "Open daily", "Getting here", "Open live directions", "Holiday hours may vary; please refer to our Google Business Profile.", "This website provides Google Maps directions only.", "View the suggested route from your current location to Savoy Cigar Flagship."],
    contact: ["Phone & Social", "Follow Savoy Cigar on Facebook and Instagram for the latest news and updates.", "Visit official Facebook", "Visit official Instagram"],
    notice: ["Age & Legal Notice", "This website provides information about the physical store, its space, and tasting knowledge only. It does not offer online tobacco sales. Entry and tobacco purchases must comply with Taiwan law and store policies; staff may request identification where age is in question.", "Tobacco products are prohibited for persons under 20", "Smoking is harmful to health"], footerAddress: "No. 17, Xintian Rd., Xinxing Dist., Kaohsiung", health: "Smoking is harmful to health  |  Smoking during pregnancy may cause premature birth and low birth weight  |  Tobacco products are prohibited for persons under 20",
  },
} as const;

type Locale = keyof typeof copy;
const galleryPhotos = ["/savoy-main-lounge.jpg", "/savoy-lounge-floral-wall.jpg", "/savoy-display-gallery.jpg", "/savoy-art-seating-corner.jpg", "/savoy-lit-display-room.jpg", "/savoy-interior-overview.jpg", "/savoy-lounge-art-wall.jpg"];
const galleryClasses = ["space-photo-main", "space-photo-tall", "", "", "", "space-photo-wide", ""];

export default function Home() {
  const [lang, setLang] = useState<Locale>(() => typeof window !== "undefined" && localStorage.getItem("savoy-language") === "en" ? "en" : "zh");
  useEffect(() => { document.documentElement.lang = lang === "zh" ? "zh-Hant" : "en"; localStorage.setItem("savoy-language", lang); }, [lang]);
  const t = copy[lang];
  const setLocale = (locale: Locale) => setLang(locale);
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessJsonLd) }} />
    <div className="legal-bar">{t.legal}</div>
    <header className="nav shell">
      <a className="brand" href="#top" aria-label="Savoy Cigar home"><Image className="brand-logo" src="/savoy-logo.svg" alt="Savoy Cigar" width={310} height={61} priority /></a>
      <nav aria-label="Main navigation"><a href="#about">{t.nav[0]}</a><a href="#experience">{t.nav[1]}</a><a href="#guide">{t.nav[2]}</a><a href="#knowledge">{t.nav[3]}</a><a href="#visit">{t.nav[4]}</a></nav>
      <div className="nav-tools"><div className="language-toggle" role="group" aria-label="Language"><button className={lang === "zh" ? "active" : ""} onClick={() => setLocale("zh")}>中文</button><span>/</span><button className={lang === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button></div><a className="nav-cta" href={MAPS_URL} target="_blank" rel="noreferrer">{t.navigate} <span>↗</span></a></div>
    </header>
    <section className="hero" id="top"><Image className="hero-image" src="/savoy-storefront.jpeg" alt={lang === "zh" ? "沙懷雪茄館旗艦店夜間門面" : "Savoy Cigar Flagship storefront at night"} fill priority sizes="100vw" /><div className="hero-shade" /><div className="hero-copy shell"><p className="eyebrow"><span /> SAVOY CIGAR · KAOHSIUNG</p><h1>{t.hero[0]}<br /><em>{t.hero[1]}</em></h1><p className="lead">{t.hero[2]}</p><div className="hero-actions"><a className="button primary" href={MAPS_URL} target="_blank" rel="noreferrer"><IconPin /> {t.maps}</a><a className="button secondary" href="tel:+88672817778"><IconPhone /> 07-281-7778</a></div><div className="quick-facts"><span><b>01</b> {t.address[0]}</span><span><b>02</b> {t.address[1]}</span><span><b>03</b> {t.address[2]}</span></div></div></section>
    <section className="manifesto" id="about"><div className="shell manifesto-grid"><p className="section-no">01 / ABOUT</p><div><p className="eyebrow dark"><span /> {t.about[0]}</p><h2>{t.about[1]}<br />{t.about[2]}</h2></div><p className="body-copy">{t.about[3]}</p></div></section>
    <section className="experience shell" id="experience"><div className="section-heading space-heading"><div><p className="eyebrow"><span /> 02 / THE SPACE</p><h2>{t.space[0]}</h2></div><p>{t.space[1]}</p></div><div className="space-highlights">{t.spaceCards.map((card, i) => <article key={card[0]}><small>0{i + 1} · {["LOUNGE", "CORNER", "DISPLAY"][i]}</small><h3>{card[0]}</h3><p>{card[1]}</p></article>)}</div><div className="space-gallery" aria-label="Savoy Cigar interior gallery">{galleryPhotos.map((photo, i) => <figure className={`space-photo ${galleryClasses[i]}`} key={photo}><Image src={photo} alt={t.gallery[i][1]} fill sizes="(max-width: 700px) 100vw, 40vw" /><figcaption><span>{["MAIN LOUNGE", "SEATING AREA", "DISPLAY", "ART CORNER", "GALLERY", "INTERIOR", "DETAIL"][i]}</span>{t.gallery[i][0]}</figcaption></figure>)}</div></section>
    <section className="guide-section" id="guide"><div className="shell"><div className="section-heading light"><div><p className="eyebrow dark"><span /> 03 / FIRST VISIT</p><h2>{t.guide[0]}</h2></div><p>{t.guide[1]}</p></div><div className="steps">{t.guideCards.map((card, i) => <article key={card[0]}><b>0{i + 1}</b><h3>{card[0]}</h3><p>{card[1]}</p></article>)}</div></div></section>
    <section className="knowledge shell" id="knowledge"><div className="knowledge-image"><Image src="/cigar-knowledge-source.png" alt={lang === "zh" ? "雪茄、雪茄盒與品鑑托盤" : "Cigar, cigar box, and tasting tray"} fill sizes="(max-width: 900px) 100vw, 42vw" /></div><div className="knowledge-copy"><p className="eyebrow"><span /> 04 / CIGAR KNOWLEDGE</p><h2>{t.knowledge[0]}</h2>{t.knowledge.slice(1).map((item, i) => <details open={i === 0} key={item[0]}><summary>{item[0]}</summary><p>{item[1]}</p></details>)}</div></section>
    <section className="visit" id="visit"><div className="shell"><div className="section-heading"><div><p className="eyebrow"><span /> 05–07 / PLAN YOUR VISIT</p><h2>{t.visit[0]}</h2></div><p>{t.visit[1]}</p></div><div className="visit-cards"><article><small>OPENING HOURS</small><h3>{t.visit[2]}</h3><strong>13:30–02:30</strong><p>{t.visit[5]}</p></article><article><small>ADDRESS</small><h3>{t.visit[3]}</h3><strong>{lang === "zh" ? <>高雄市新興區<br />新田路17號</> : <>No. 17, Xintian Rd.<br />Xinxing Dist., Kaohsiung</>}</strong><p>{t.visit[6]}</p></article><article className="map-card"><small>GOOGLE MAPS</small><h3>{t.visit[4]}</h3><p>{t.visit[7]}</p><a href={MAPS_URL} target="_blank" rel="noreferrer"><IconPin /> {t.maps} <span>↗</span></a></article></div></div></section>
    <section className="contact shell" id="contact"><div><p className="eyebrow"><span /> 08 / CONTACT & SOCIAL</p><h2>{t.contact[0]}</h2><p>{t.contact[1]}</p></div><div className="contact-links"><a href="tel:+88672817778"><span>PHONE</span>07-281-7778 ↗</a><a href={FACEBOOK_URL} target="_blank" rel="noreferrer"><span>FACEBOOK</span>{t.contact[2]} ↗</a><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer"><span>INSTAGRAM</span>{t.contact[3]} ↗</a></div></section>
    <section className="compliance" id="compliance"><div className="shell compliance-grid"><p className="section-no">10 / NOTICE</p><div><h2>{t.notice[0]}</h2><p>{t.notice[1]}</p></div><strong>{t.notice[2]}<br />{t.notice[3]}</strong></div></section>
    <footer className="footer"><div className="shell footer-row"><div className="brand inverse"><Image className="brand-logo footer-logo" src="/savoy-logo-light.svg" alt="Savoy Cigar" width={310} height={61} /></div><div><p>{t.footerAddress}</p><p>07-281-7778</p></div><small>© 2026 SAVOY CIGAR. ALL RIGHTS RESERVED.</small></div><div className="health-warning">{t.health}</div></footer>
    <div className="mobile-dock"><a href={MAPS_URL} target="_blank" rel="noreferrer"><IconPin />{t.navigate}</a><a href="tel:+88672817778"><IconPhone />{t.call}</a><button onClick={() => setLocale(lang === "zh" ? "en" : "zh")}>◎ {lang === "zh" ? "EN" : "中文"}</button></div>
  </main>;
}

function IconPin() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s7-6.1 7-12A7 7 0 1 0 5 9c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.4"/></svg>; }
function IconPhone() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 3.5 10 7.8 8.3 10c1.2 2.4 3.1 4.3 5.5 5.5l2.2-1.7 4.4 2.8-.8 3.3c-.2.8-1 1.3-1.8 1.2C10 20.1 3.9 14 2.9 6.2c-.1-.8.4-1.6 1.2-1.8l3.1-.9Z"/></svg>; }
